using System;
using System.Collections.Generic;
using System.Linq;
using Autodesk.Revit.DB;
using ZoningFloorArea.Models;

namespace ZoningFloorArea.Services
{
    public class RevitAreaExtractor
    {
        private readonly Document _doc;

        public RevitAreaExtractor(Document doc)
        {
            if (doc == null) throw new ArgumentNullException("doc");
            _doc = doc;
        }

        public List<string> GetAreaSchemeNames()
        {
            FilteredElementCollector collector = new FilteredElementCollector(_doc).OfClass(typeof(AreaScheme));
            List<string> list = new List<string>();
            foreach (AreaScheme s in collector)
            {
                list.Add(s.Name);
            }
            list.Sort();
            return list;
        }

        public List<string> GetAvailableAreaParameters()
        {
            List<string> paramNames = new List<string>();
            paramNames.Add("Deductions");
            paramNames.Add("Deduction");
            paramNames.Add("Building");
            paramNames.Add("Name");
            paramNames.Add("Comments");
            paramNames.Add("Area Type");
            paramNames.Add("Number");

            // Scan existing areas
            FilteredElementCollector collector = new FilteredElementCollector(_doc)
                .OfCategory(BuiltInCategory.OST_Areas)
                .WhereElementIsNotElementType();

            foreach (Area a in collector)
            {
                foreach (Parameter p in a.Parameters)
                {
                    if (p.Definition != null && !string.IsNullOrEmpty(p.Definition.Name))
                    {
                        if (!paramNames.Contains(p.Definition.Name))
                        {
                            paramNames.Add(p.Definition.Name);
                        }
                    }
                }
                break; // One sample area is enough for instance parameters
            }

            // Also scan document parameter bindings
            try
            {
                BindingMap map = _doc.ParameterBindings;
                DefinitionBindingMapIterator it = map.ForwardIterator();
                while (it.MoveNext())
                {
                    InstanceBinding ib = it.Current as InstanceBinding;
                    if (ib != null && ib.Categories != null && ib.Categories.Contains(_doc.Settings.Categories.get_Item(BuiltInCategory.OST_Areas)))
                    {
                        if (!paramNames.Contains(it.Key.Name))
                        {
                            paramNames.Add(it.Key.Name);
                        }
                    }
                }
            }
            catch { }

            return paramNames;
        }

        public bool CreateAreaSharedParameter(string paramName)
        {
            if (string.IsNullOrWhiteSpace(paramName)) paramName = "Deductions";
            try
            {
                // Check if parameter binding already exists in document
                BindingMap map = _doc.ParameterBindings;
                DefinitionBindingMapIterator it = map.ForwardIterator();
                while (it.MoveNext())
                {
                    if (string.Equals(it.Key.Name, paramName, StringComparison.OrdinalIgnoreCase))
                    {
                        return true; // Already exists!
                    }
                }

                // Create or ensure temporary shared parameter file
                string tempFile = System.IO.Path.Combine(System.IO.Path.GetTempPath(), "BauTools_SharedParams.txt");
                if (!System.IO.File.Exists(tempFile))
                {
                    System.IO.File.WriteAllText(tempFile, "# This is a temporary shared parameter file generated by BauTools\r\n*META\tVERSION\tMINVERSION\r\nMETA\t2\t1\r\n*GROUP\tID\tNAME\r\nGROUP\t1\tBauToolsZoning\r\n*PARAM\tGUID\tNAME\tDATATYPE\tDATACONTROLCAT\tGROUP\tDESCRIPTION\tUSERMODIFIABLE\tHIDEWHENNOVALUE\r\n");
                }

                string originalSharedParamFile = _doc.Application.SharedParametersFilename;
                _doc.Application.SharedParametersFilename = tempFile;

                DefinitionFile defFile = _doc.Application.OpenSharedParameterFile();
                if (defFile == null) return false;

                DefinitionGroup defGroup = defFile.Groups.get_Item("BauToolsZoning");
                if (defGroup == null)
                {
                    defGroup = defFile.Groups.Create("BauToolsZoning");
                }

                Definition definition = defGroup.Definitions.get_Item(paramName);
                if (definition == null)
                {
                    ExternalDefinitionCreationOptions opt = new ExternalDefinitionCreationOptions(paramName, SpecTypeId.String.Text);
                    opt.Description = "BauTools Zoning Deduction Category Identifier";
                    opt.UserModifiable = true;
                    definition = defGroup.Definitions.Create(opt);
                }

                if (!string.IsNullOrEmpty(originalSharedParamFile) && System.IO.File.Exists(originalSharedParamFile))
                {
                    _doc.Application.SharedParametersFilename = originalSharedParamFile;
                }

                Category areaCat = _doc.Settings.Categories.get_Item(BuiltInCategory.OST_Areas);
                CategorySet catSet = _doc.Application.Create.NewCategorySet();
                catSet.Insert(areaCat);

                InstanceBinding instanceBinding = _doc.Application.Create.NewInstanceBinding(catSet);

                using (Transaction t = new Transaction(_doc, "Create Zoning Parameter: " + paramName))
                {
                    t.Start();
                    _doc.ParameterBindings.Insert(definition, instanceBinding, GroupTypeId.Data);
                    t.Commit();
                }

                return true;
            }
            catch (Exception ex)
            {
                System.Diagnostics.Debug.WriteLine("Error creating parameter: " + ex.Message);
                return false;
            }
        }

        public List<AreaDataModel> ExtractAreas(MappingConfig config)
        {
            List<AreaDataModel> results = new List<AreaDataModel>();

            FilteredElementCollector collector = new FilteredElementCollector(_doc)
                .OfCategory(BuiltInCategory.OST_Areas)
                .WhereElementIsNotElementType();

            foreach (Area area in collector)
            {
                if (area.Area <= 0) continue;

                string schemeName = area.AreaScheme != null ? area.AreaScheme.Name : string.Empty;
                string levelName = area.Level != null ? area.Level.Name : "Unassigned";
                double levelElevation = area.Level != null ? area.Level.Elevation : 0.0;

                // Extract Building Name
                string bldgName = GetParameterStringValue(area, config.BuildingParameterName);
                if (string.IsNullOrEmpty(bldgName))
                {
                    bldgName = GetParameterStringValue(area, "Building");
                }
                if (string.IsNullOrEmpty(bldgName))
                {
                    bldgName = string.IsNullOrEmpty(config.BuildingName) ? "BUILDING C" : config.BuildingName;
                }

                // Extract Deduction Type
                string deductionType = GetParameterStringValue(area, config.DeductionTypeParameterName);
                if (string.IsNullOrEmpty(deductionType))
                {
                    deductionType = GetParameterStringValue(area, "Deduction");
                }
                if (string.IsNullOrEmpty(deductionType))
                {
                    deductionType = area.Name;
                }

                string usageCategory = GetParameterStringValue(area, config.UsageCategoryParameterName);
                if (string.IsNullOrEmpty(usageCategory))
                {
                    string comm = GetParameterStringValue(area, "Comments");
                    string name = area.Name ?? string.Empty;
                    if (comm.IndexOf("Commercial", StringComparison.OrdinalIgnoreCase) >= 0 ||
                        comm.IndexOf("Comercial", StringComparison.OrdinalIgnoreCase) >= 0 ||
                        comm.IndexOf("Retail", StringComparison.OrdinalIgnoreCase) >= 0 ||
                        name.IndexOf("Commercial", StringComparison.OrdinalIgnoreCase) >= 0 ||
                        name.IndexOf("Comercial", StringComparison.OrdinalIgnoreCase) >= 0 ||
                        name.IndexOf("Retail", StringComparison.OrdinalIgnoreCase) >= 0)
                    {
                        usageCategory = "Commercial";
                    }
                    else
                    {
                        usageCategory = "Residential";
                    }
                }
                else if (usageCategory.IndexOf("Commercial", StringComparison.OrdinalIgnoreCase) >= 0 ||
                         usageCategory.IndexOf("Comercial", StringComparison.OrdinalIgnoreCase) >= 0 ||
                         usageCategory.IndexOf("Retail", StringComparison.OrdinalIgnoreCase) >= 0)
                {
                    usageCategory = "Commercial";
                }
                else
                {
                    usageCategory = "Residential";
                }

                AreaDataModel model = new AreaDataModel();
                model.ElementId = area.Id.ToString();
                model.Name = area.Name;
                model.AreaValue = area.Area;
                model.LevelName = levelName;
                model.LevelElevation = levelElevation;
                model.AreaSchemeName = schemeName;
                model.DeductionType = deductionType;
                model.UsageCategory = usageCategory;
                model.BuildingName = bldgName.Trim().ToUpper();

                results.Add(model);
            }

            return results;
        }

        private string GetParameterStringValue(Area area, string paramName)
        {
            if (string.IsNullOrEmpty(paramName)) return string.Empty;

            Parameter p = area.LookupParameter(paramName);
            if (p == null && string.Equals(paramName, "Name", StringComparison.OrdinalIgnoreCase))
            {
                p = area.get_Parameter(BuiltInParameter.ROOM_NAME);
            }

            if (p == null) return string.Empty;

            switch (p.StorageType)
            {
                case StorageType.String:
                    return p.AsString() ?? string.Empty;
                case StorageType.ElementId:
                    Element el = _doc.GetElement(p.AsElementId());
                    return el != null ? el.Name : string.Empty;
                default:
                    return p.AsValueString() ?? string.Empty;
            }
        }
    }
}
